version: '3.3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./client/dist:/app
      - /home/www/letsencrypt:/home/www/letsencrypt
      - ./logs:/var/log/nginx
      - ./certbotData:/etc/letsencrypt/live/jankenrating.tk
      - ./dhparam.pem:/etc/nginx/ssl/dhparam.pem
    ports:
      - 80:80
      - 443:443
    links:
      - minio
      - server

  minio:
    image: minio/minio
    volumes:
      - ./minio/data:/data
    command: server /data
    ports:
      - 9000:9000
    env_file: 
      - ./.env

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/janken-rating;
      /usr/bin/mc policy set public myminio/janken-rating/icons;
      exit 0;
      "

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    env_file: 
      - ./.env
    environment:
      - MYSQL_DATABASE=janken_rating
      - TZ=Asia/Tokyo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: 
      - ./.env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    links:
      - mysql
    ports:
      - 8080:80

  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - mysql
      - minio
    env_file: 
      - ./.env

  client_dev:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    links:
      - server
    ports:
      - 3000:8080

